name: Docker build & push
on:
  push:
    branches: 
    - master
jobs:
  build:
    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKER_PAT: ${{ secrets.DOCKERHUB_PAT }}
      REPO_NAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: docker build
      run: make build_image
    - name: docker push
      run: make push_image