name: Docker build & push
on:
  push:
    branches: 
    - master
jobs:
  build:
    env:
      DOCKER_HOST: "index.docker.io/v1"
      DOCKER_PAT: ${{ secrets.DOCKERHUB_PAT }}
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: docker build
      run: make build_image
