name: Docker build & push
on:
  push:
    branches: 
    - master
env:
  DOCKER_HOST: "dockerhub"
  DOCKER_PAT: ${{ secrets.DOCKERHUB_PAT }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: docker build
      run: make build_image
